# Generated by Django 3.0.5 on 2021-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=100, null=True)),
                ('Model', models.CharField(max_length=100, null=True)),
                ('Variant', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
