# Generated by Django 3.0.5 on 2021-03-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
