# Generated by Django 3.0.5 on 2021-07-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.IntegerField(blank=True)),
                ('product_id', models.IntegerField(blank=True)),
                ('sku_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('salt_name', models.CharField(max_length=100)),
                ('drug_form', models.CharField(max_length=100)),
                ('Pack_size', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('product_banned_flag', models.BooleanField(default=False)),
                ('unit', models.CharField(max_length=100)),
                ('price_per_unit', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='details',
            name='model',
        ),
        migrations.RemoveField(
            model_name='details',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
