# Generated by Django 3.0.5 on 2021-07-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0004_auto_20210713_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='product_banned_flag',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
