# Generated by Django 3.0.5 on 2021-07-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0005_auto_20210713_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Pack_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='drug_form',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price_per_unit',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='salt_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sku_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
