# Generated by Django 3.0.5 on 2021-07-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0008_auto_20210713_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Pack_size',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='drug_form',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='salt_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sku_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
